"""Add sites and sensor readings tables

Revision ID: 31e7ad360087
Revises: ab77bf79860a
Create Date: 2026-09-10 03:33:54.685126

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31e7ad360087"
down_revision: str | Sequence[str] | None = "ab77bf79860a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=False),
        sa.Column("location_lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("location_lng", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id"),
    )
    op.create_table(
        "sensor_readings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("cell_voltage", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("cell_current", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("ambient_temp", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("humidity", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("tilt_x", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("tilt_y", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("tilt_z", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("heading", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("device_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["site_id"], ["sites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensor_readings")
    op.drop_table("sites")
    # ### end Alembic commands ###
